from tkinter import*
#Janela:
J = Tk()
LT = J.winfo_screenwidth()
AT = J.winfo_screenheight()
l = 420
a = 420
x = int(LT/2 - l/2)
y = int(AT/2 - a/2)
J.geometry(f"{l-105}x{a-175}+{x}+{y}")
n = StringVar()
n.set("opa")
n1 = StringVar()
n1.set("meu mano")
n0 = StringVar()
nR = StringVar()
nt0 = StringVar()
nt = StringVar()
F = Frame(J).grid(pady=40,padx=20)
Label(F,bg="black",fg="green",textvariable=n,width=11,height=5).grid(row=0,column=0)
Label(F,bg="black",fg="green",textvariable=n1,width=11,height=5).grid(row=0,column=1)
Label(F,bg="black",fg="green",textvariable=n0,width=11,height=5).grid(row=0,column=2)
Label(F,bg="black",fg="green",textvariable=nt,width=11,height=5).grid(row=0,column=3)
Button(F,bg = "grey",fg="white",height= 2,width = 10,text="1").grid(column=0,row=1)
Button(F,bg = "grey",fg="white",height= 2,width = 10,text="2").grid(column=1,row=1)
Button(F,bg = "grey",fg="white",height= 2,width = 10,text="3").grid(column=2,row=1)
Button(F,bg = "grey",fg="white",height= 2,width = 10,text="4").grid(column=0,row=2)
Button(F,bg = "grey",fg="white",height= 2,width = 10,text="5").grid(column=1,row=2)
Button(F,bg = "grey",fg="white",height= 2,width = 10,text="6").grid(column=2,row=2)
Button(F,bg = "grey",fg="white",height= 2,width = 10,text="7").grid(column=0,row=3)
Button(F,bg = "grey",fg="white",height= 2,width = 10,text="8").grid(column=1,row=3)
Button(F,bg = "grey",fg="white",height= 2,width = 10,text="9").grid(column=2,row=3)
Button(F,bg = "grey",fg="white",height= 2,width = 10,text="0").grid(column=1,row=4)
Button(F,bg = "grey",fg="white",height= 2,width = 10,text="+").grid(column=3,row=1)
Button(F,bg = "grey",fg="white",height= 2,width = 10,text="-").grid(column=3,row=2)
Button(F,bg = "grey",fg="white",height= 2,width = 10,text="x").grid(column=3,row=3)
Button(F,bg = "grey",fg="white",height= 2,width = 10,text="/").grid(column=3,row=4)
Button(F,bg = "grey",fg="white",height= 2,width = 10,text="=").grid(column=2,row=4)
Button(F,bg = "grey",fg="white",height= 2,width = 10,text="Del").grid(column=0,row=4)
J.mainloop()
#*******************************************
